---
language: python

services:
  - docker

script:
  - pip install molecule
  - pip install testinfra==3.0.4
  - pip install docker-py
  - molecule lint
  - molecule create
  - molecule converge
  - molecule verify
