---
# tasks file for gitea
- name: Download gitea
  get_url:
    url: https://dl.gitea.io/gitea/1.3.2/gitea-1.3.2-linux-amd64
    dest: /usr/local/bin/gitea
    mode: 0555

- name: Create group git
  group:
    name: git
    state: present

- name: Create git user
  user:
    name: git
    group: git
    state: present

- name: copy gitea service
  copy:
    src: gitea.service
    dest: /etc/systemd/system/gitea.service
    # owner: foo
    # group: foo
    mode: 0655

- name: ensure gitea config dir exist
  file:
    path: /etc/gitea
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure git is installed
  apt:
    name: git

- name: ensure gitea work dir exist
  file:
    path: /var/lib/gitea
    state: directory
    owner: git
    group: git
    mode: 0755

- name: copy gitea config
  copy:
    src: app.ini
    dest: /etc/gitea/app.ini
    owner: root
    group: root
    mode: 0444

- name: ensure gitea gitea/custom dir exist
  file:
    path: /var/lib/gitea/custom
    state: directory
    owner: git
    group: git
    mode: 0755

- name: Ensure start and enable gitea
  service:
    name: gitea
    state: started
    enabled: yes 
